<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Bootstrap.aspx.cs" Inherits="DXRDWForDevsSample.Bootstrap" %>

<!DOCTYPE html>
<html lang="en">
<head runat="server">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="My description">
    <meta name="author" content="Don Wibier">
    <link rel="icon" href="imgs/favicon.ico">

    <title>Bootstrap page</title>

    <%-- Bootstrap core CSS --%>
    <link href="/css-bootstrap/bootstrap.min.css" rel="stylesheet">
    <link href="/css-bootstrap/bootstrap-theme.min.css" rel="stylesheet">
    <link href="/css-bootstrap/site.min.css" rel="stylesheet" />

    <%-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries --%>
    <!--[if lt IE 9]>
      <script src="//oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="//oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Custom styles for this template -->
    <%--<link href="carousel.css" rel="stylesheet">--%>
</head>
<body>
    <form id="form1" runat="server">
        <nav class="navbar navbar-inverse">
            <div class="container">
                <div class="navbar-header header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <div class="logo-slogan">
                        <h1 class="logo"><a runat="server" href="~/">My Site, the responsive sample project</a></h1>
                        <a class="banner" href="#"></a>
                    </div>
                    <%--<a class="navbar-brand" href="#">Project name</a>--%>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <div class="navbar-form navbar-right">
                        <div class="form-group">
                            <input type="text" placeholder="Email" class="form-control">
                        </div>
                        <div class="form-group">
                            <input type="password" placeholder="Password" class="form-control">
                        </div>
                        <button type="submit" class="btn btn-success">Sign in</button>
                    </div>
                </div>
                <!--/.navbar-collapse -->
            </div>
        </nav>
        <div class="container">
            <div id="bannerContainer" class="col-md-12">
                <dx:ASPxImageSlider ID="ASPxImageSlider1" runat="server" ClientInstanceName="HomeBanner" EnableViewState="false"
                    BinaryImageCacheFolder="~\Thumb\" Width="100%" Height="350px">
                    <SettingsImageArea AnimationType="Slide" EnableLoopNavigation="True" ImageSizeMode="FillAndCrop" />
                    <SettingsNavigationBar Mode="Dots" />
                    <SettingsSlideShow AutoPlay="True" PausePlayingWhenMouseOver="True" />
                    <SettingsAutoGeneratedImages ImageCacheFolder="~\Temp\Thumbs\" />
                    <Items>
                        <dx:ImageSliderItem ImageUrl="images/banner1.jpg" Text="Banner 1"></dx:ImageSliderItem>
                        <dx:ImageSliderItem ImageUrl="images/banner2.jpg" Text="Banner 2"></dx:ImageSliderItem>
                    </Items>
                </dx:ASPxImageSlider>
            </div>
        </div>
        <div class="container">
            
            <div class="row">
                <div class="col-md-4">
                    <h2>Heading</h2>
                    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
                    <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
                </div>
                <div class="col-md-4">
                    <h2>Heading</h2>
                    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
                    <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
                </div>
                <div class="col-md-4">
                    <h2>Heading</h2>
                    <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
                    <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
                </div>
            </div>

            <hr>

            <footer>
                <p>&copy; Company 2014</p>
            </footer>
        </div>
        <!-- /container -->

    </form>
    <script src="Scripts/jquery-2.1.4.js"></script>
    <script src="Scripts/bootstrap.js"></script>

    <script src="Scripts/Site.tools.js"></script>

</body>
</html>
