<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Skeleton.aspx.cs" Inherits="DXRDWForDevsSample.Skeleton" %>

<!DOCTYPE html>
<html lang="en">
<head runat="server">
    <!-- Basic Page Needs -->
    <meta charset="utf-8">
    <title>Your page title here :)</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Mobile Specific Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- FONT -->
    <link href="//fonts.googleapis.com/css?family=Raleway:400,300,600" rel="stylesheet" type="text/css">
    <!-- CSS  -->
    <link rel="stylesheet" href="/css/normalize.css">
    <link rel="stylesheet" href="/css/skeleton.css">
    <link rel="stylesheet" href="/css/icons.css" />
    <link rel="stylesheet" href="/css/site.min.css" />
    <!-- Favicon -->
    <link rel="icon" type="image/png" href="images/favicon.png">
</head>
<body>
    <form id="form1" runat="server">
        <asp:SiteMapDataSource runat="server" ID="DSSitemap" ShowStartingNode="false" />
        <%-- Primary Page Layout   --%>
        <div class="page">
            <div class="content">
                <%-- Header --%>
                <div class="section header">
                    <div class="container">
                        <div class="row">
                            <div class="twelve columns">
                                <div class="logo-slogan">
                                    <h1 class="logo"><a runat="server" href="~/">My Site, the responsive sample project</a></h1>
                                    <a class="banner" href="#"></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <%-- Navigation --%>
                <div class="section navigation">
                    <div class="container">
                        <div class="row">
                            <div class="twelve columns normal">
                                <div class="u-pull-left">
                                    <dx:ASPxMenu runat="server" ID="dxMainMenu" CssClass="site-navigation" EnableViewState="false"
                                        AutoPostBack="false" DataSourceID="DSSitemap" ItemAutoWidth="false">
                                    </dx:ASPxMenu>
                                </div>
                            </div>
                            <%-- Hamburger icon --%>
                            <div class="twelve columns compact">
                                <div class="compact-menu-container u-pull-left">
                                    <a href="#" class="compact-menu" data-navigate-action="toggle-hamburger-left">
                                        <span class="icon-menu"></span>
                                    </a>
                                    <a href="#" class="compact-menu" data-navigate-action="toggle-hamburger-right">
                                        <span>Test right</span>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <%-- Homepage banner --%>
                <div id="home" class="section banner">
                    <div class="container">
                        <div class="row">
                            <div id="bannerContainer" class="twelve columns">
                                <dx:ASPxImageSlider ID="ASPxImageSlider1" runat="server" ClientInstanceName="HomeBanner" EnableViewState="false"
                                    BinaryImageCacheFolder="~\Thumb\" Width="100%" Height="350px">
                                    <SettingsImageArea AnimationType="Slide" EnableLoopNavigation="True" ImageSizeMode="FillAndCrop" />
                                    <SettingsNavigationBar Mode="Dots" />
                                    <SettingsSlideShow AutoPlay="True" PausePlayingWhenMouseOver="True" />
                                    <SettingsAutoGeneratedImages ImageCacheFolder="~\Temp\Thumbs\" />
                                    <Items>
                                        <dx:ImageSliderItem ImageUrl="images/banner1.jpg" Text="Banner 1"></dx:ImageSliderItem>
                                        <dx:ImageSliderItem ImageUrl="images/banner2.jpg" Text="Banner 2"></dx:ImageSliderItem>
                                    </Items>
                                </dx:ASPxImageSlider>
                            </div>
                            <div class="clear"></div>
                        </div>
                    </div>
                </div>
                <%-- Homepage content --%>
                <div class="section content">
                    <div class="container">
                        <div class="row margin-top">
                            <div class="one-third column">
                                <div class="content-block">
                                    <span class="header">1st column</span>
                                    <p>
                                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ut turpis sem. Praesent viverra pharetra consequat. 
                                        Vestibulum vitae lobortis leo. Ut a ante risus. Ut gravida leo id sapien ultrices euismod. 
                                        Suspendisse pellentesque, lectus sed tristique finibus, diam dolor semper diam, vel aliquet enim risus ac quam. 
                                    </p>
                                </div>
                            </div>
                            <div class="one-third column">
                                <div class="content-block">
                                    <span class="header">2nd column</span>
                                    <p>
                                        Nunc maximus, justo sit amet condimentum tincidunt, diam lectus facilisis justo, quis egestas diam purus vitae quam. 
                                        Nulla nec sem eu lorem scelerisque lacinia. Donec commodo eros lacinia, fringilla orci eget, convallis mi. 
                                        Nunc mattis, lectus ac mattis vulputate, nisl sapien eleifend mauris, et auctor tellus risus a lectus.
                                    </p>
                                </div>
                            </div>
                            <div class="one-third column">
                                <div class="content-block">
                                    <span class="header">3rth column</span>
                                    <p>
                                        Suspendisse aliquam lectus a nunc suscipit, vitae mollis risus luctus. 
                                        Praesent faucibus, ante eu dictum elementum, odio nisi tempus nunc, et auctor dolor urna quis ligula. 
                                        Cras quis mattis tellus. Etiam euismod at felis nec tincidunt. Donec venenatis lacinia bibendum. 
                                        Aenean tincidunt tortor vitae erat dictum, sit amet scelerisque nisi facilisis.
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <%-- Homepage content --%>
            </div>
        </div>
        <div class="section footer">
            <div class="container">
                <div class="row">
                    <div class="twelve columns">
                        <span class="disclaimer">Don Wibier &copy; 2015</span>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Document -->
        <%-- Left hamburger menu --%>
        <div class="left-hamburger navigation">
            <div class="side-menu-inner">
                <div class="back-container" data-navigate-action="toggle-hamburger-left">
                    <span class="icon-circle-left" style="margin-right: 4px"></span>Menu
                </div>
                <dx:ASPxMenu runat="server" ID="dxSiteMenu" CssClass="site-navigation" EnableViewState="false"
                    Orientation="Vertical" SeparatorHeight="0" AutoPostBack="false"
                    ItemAutoWidth="false" Width="100%" DataSourceID="DSSiteMap">
                </dx:ASPxMenu>
            </div>
        </div>
        <%-- Right hamburger menu --%>
        <div class="right-hamburger navigation">
            <div class="side-menu-inner">
                <div class="back-container" data-navigate-action="toggle-hamburger-right">
                    <span class="icon-circle-left" style="margin-right: 4px"></span>Menu
                </div>
                <p>
                    This is our right hamburger menu :-)
                </p>
            </div>
        </div>
    </form>
    <script src="Scripts/modernizr-2.8.3.js"></script>
    <script src="Scripts/jquery-2.1.4.js"></script>
    <script src="Scripts/Site.tools.js"></script>
</body>
</html>
